# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Medicine, Heresy, and Freedom of Thought in Sixteenth-Century Italy
description: >- # this means to ignore newlines until "baseurl:"
  The website provides an overview of my post-doc research project, 
  funded under the 2020 Horizion programme and carried out between 
  Stanford University and the University of Verona, “Heresy, Medicine 
  and Freedom of thought: a network of dissident physicians in the 
  confessional age”. Relying on both digital humanities tools and a 
  traditional scholarly approach, the project explores the local, 
  national and transnational networks of a sample of around 200 hundred 
  Italian heretical physicians. Focusing on the understanding of historical 
  networks, my goal is to investigate the relationship between medicine 
  and heresy in both intellectual and social respects. The website contains 
  the network visualisations, the spreadsheets from which these visualisations 
  come, a description of the project and the researcher, and a section about 
  the dissemination activities (inside and outside academia) related to the project. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
    load_paths:
        - _sass
        - node_modules
exclude: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
